CREATE TABLE IF NOT EXISTS "rss-translate-app_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "rss-translate-app_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rss-translate-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_rssOrigin" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"link" varchar(255) NOT NULL,
	"job_id" varchar(255),
	"job_status" varchar(255),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_rssTranslate" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"rss_origin" varchar(255) NOT NULL,
	"translate_origin" varchar(255) NOT NULL,
	"translate_prompt" varchar(255) NOT NULL,
	"language" varchar(255) NOT NULL,
	"cron" varchar(255) NOT NULL,
	"enabled" boolean NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"job_id" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_rssTranslateData" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"feed" json,
	"rss_translate_id" varchar(255) NOT NULL,
	"job_id" varchar(255),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_rssTranslateDataItem" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"origin" json,
	"data" json,
	"link" varchar(255) NOT NULL,
	"rss_translate_data_id" varchar(255) NOT NULL,
	"job_id" varchar(255),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_rssData" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"data" json NOT NULL,
	"job_id" varchar(255),
	"rss_origin_id" varchar(255) NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_translateOrigin" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"base_url" varchar(255),
	"api_key" varchar(255) NOT NULL,
	"model" varchar(255) NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_translatePrompt" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"prompt" text NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rss-translate-app_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "rss-translate-app_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_account" ADD CONSTRAINT "rss-translate-app_account_user_id_rss-translate-app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_post" ADD CONSTRAINT "rss-translate-app_post_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssOrigin" ADD CONSTRAINT "rss-translate-app_rssOrigin_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslate" ADD CONSTRAINT "rss-translate-app_rssTranslate_rss_origin_rss-translate-app_rssOrigin_id_fk" FOREIGN KEY ("rss_origin") REFERENCES "public"."rss-translate-app_rssOrigin"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslate" ADD CONSTRAINT "rss-translate-app_rssTranslate_translate_origin_rss-translate-app_translateOrigin_id_fk" FOREIGN KEY ("translate_origin") REFERENCES "public"."rss-translate-app_translateOrigin"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslate" ADD CONSTRAINT "rss-translate-app_rssTranslate_translate_prompt_rss-translate-app_translatePrompt_id_fk" FOREIGN KEY ("translate_prompt") REFERENCES "public"."rss-translate-app_translatePrompt"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslate" ADD CONSTRAINT "rss-translate-app_rssTranslate_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslateData" ADD CONSTRAINT "rss-translate-app_rssTranslateData_rss_translate_id_rss-translate-app_rssTranslate_id_fk" FOREIGN KEY ("rss_translate_id") REFERENCES "public"."rss-translate-app_rssTranslate"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslateData" ADD CONSTRAINT "rss-translate-app_rssTranslateData_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslateDataItem" ADD CONSTRAINT "rss-translate-app_rssTranslateDataItem_rss_translate_data_id_rss-translate-app_rssTranslateData_id_fk" FOREIGN KEY ("rss_translate_data_id") REFERENCES "public"."rss-translate-app_rssTranslateData"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssTranslateDataItem" ADD CONSTRAINT "rss-translate-app_rssTranslateDataItem_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_session" ADD CONSTRAINT "rss-translate-app_session_user_id_rss-translate-app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssData" ADD CONSTRAINT "rss-translate-app_rssData_rss_origin_id_rss-translate-app_rssOrigin_id_fk" FOREIGN KEY ("rss_origin_id") REFERENCES "public"."rss-translate-app_rssOrigin"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_rssData" ADD CONSTRAINT "rss-translate-app_rssData_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_translateOrigin" ADD CONSTRAINT "rss-translate-app_translateOrigin_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rss-translate-app_translatePrompt" ADD CONSTRAINT "rss-translate-app_translatePrompt_created_by_rss-translate-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."rss-translate-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "rss-translate-app_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_by_idx" ON "rss-translate-app_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "rss-translate-app_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "rss-translate-app_session" USING btree ("user_id");